# Generated by Django 6.0.1 on 2026-02-19 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zen_mode_audio_enabled', models.BooleanField(default=False)),
                ('ai_enabled', models.BooleanField(default=False)),
                ('ollama_url', models.CharField(default='http://localhost:11434', max_length=255)),
                ('ollama_model', models.CharField(default='qwen2.5-coder:1.5b', max_length=255)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
