# Generated by Django 6.0.1 on 2026-02-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('groq', 'Groq')], default='ollama', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='groq_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=255),
        ),
    ]
